In [3]:
import numpy as np
a=np.array([[10,20,30],[50,80,70]])
print (a)
print("Array created:",a)

[[10 20 30]
 [50 80 70]]
Array created: [[10 20 30]
 [50 80 70]]


In [4]:
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
d=np.random.random((3,3))
print("\n Random values:\n",d)


 Random values:
 [[0.64820645 0.78222205 0.15517591]
 [0.57802138 0.58456917 0.47359147]
 [0.1694937  0.68931232 0.62689424]]


In [6]:
import numpy as np
e=np.arange(0,40,5)
print("\n A Sequence array with step 5:\n",e)


 A Sequence array with step 5:
 [ 0  5 10 15 20 25 30 35]


In [7]:
import numpy as np
f=np.full((3,4),(7))
print (f)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [8]:
arr=np.array([[1,2,3,4],[10,20,30,40],[11,22,33,44]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("\n reshaped array:\n",newarr)


 Original array:
 [[ 1  2  3  4]
 [10 20 30 40]
 [11 22 33 44]]

 reshaped array:
 [[ 1  2  3]
 [ 4 10 20]
 [30 40 11]
 [22 33 44]]


In [9]:
flat=arr.flatten()
print("\n Original array:\n",arr)
print("\n flattened array:\n",flat)


 Original array:
 [[ 1  2  3  4]
 [10 20 30 40]
 [11 22 33 44]]

 flattened array:
 [ 1  2  3  4 10 20 30 40 11 22 33 44]


In [10]:
arr=np.array([[1,2,3,4],[10,20,30,40],[11,22,33,44]])
print("\n number of dimensions:",arr.ndim)


 number of dimensions: 2


In [11]:
print("\n shape of the array:",arr.shape)


 shape of the array: (3, 4)


In [12]:
print("\n Array element type:",arr.dtype)


 Array element type: int32


In [15]:
newtype=arr.astype('f')
print("\n converted array element:\n",newtype)
print("\n converted array type:",newtype.dtype)


 converted array element:
 [[ 1.  2.  3.  4.]
 [10. 20. 30. 40.]
 [11. 22. 33. 44.]]

 converted array type: float32
